# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collectif POWA
email: contact@collectifpowa.org
description: > # this means to ignore newlines until "baseurl:"
  (re)donner aux jeunes
  le pouvoir d'agir
  sur leur parcours professionel

# development
baseurl: "/powa-prototype" # the subpath of your site, e.g. /blog
url: "https://collectif-powa.github.io"

# production
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://collectifpowa.org"

# Build settings
markdown: kramdown

sass:
  style: compressed
